### ISSUE TITLE
Issue with KqueueWatcher on iOS, falls back to polling. 

### ISSUE THREAD

**Issue by gordongrech** [notify-rs/notify#641]
Hello, not reporting this as a bug as I am new to this library and may be missing something myself. 

I am trying to use notify on iOS, using RecommendedWatcher is falling back to polling and selecting KqueueWatcher is giving me a build error as follows: 

```rust
    let (tx, rx) = std::sync::mpsc::channel();
    let mut watcher = notify::KqueueWatcher::new(tx, Config::default()).unwrap();
    watcher.watch(path.as_ref(), RecursiveMode::NonRecursive).unwrap();

    for res in rx {
        match res {
            Ok(event) =>  handle_job(event),
            Err(e) => log::error!("watch error: {:?}", e),
        }
    }
```

```shell
let mut watcher = notify::KqueueWatcher::new(tx, Config::default()).unwrap();
    |                               ^^^^^^^^^^^^^ could not find `KqueueWatcher` in `notify`
```

Here are my dependencies in Cargo.toml

```toml
[dependencies]
libc = "0.2"
log = "0.4.22"
notify = {version = "6.1.1", features = ["kqueue"]}
serde = {version = "1.0.210", features = ["derive"]}
serde_json = "1.0"
```

I have also tried adding kqueue and kqueue-sys but the behavior does not change.

Thanks in advance for any assistance.
